
local color = require("@adore/color")

local graphics = {}

function graphics.clearscreen(color: color.Color)
    error("Not implemented")
end
function graphics.print(text: string, x: number, y: number, fontsize: number, color: color.Color)
    error("Not implemented")
end
function graphics.circle(mode: string, x: number, y: number, radius: number, color: color.Color)
    error("Not implemented")
end

return graphics